---
- hosts: all
  become: true
  tasks:
   - name: Install Java
     yum: name="{{JavaPackageVersion}}"
   - name: Get the Java Version
     shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
     register: javaVersion
   - name: Display the Java Version
     debug: 
      var: javaVersion.stdout
....