---
- hosts: all
  become: true
  tasks: 
    - name: Create the users
      user:
        name: "{{item.usernname}}"
        create_home: "{{item.createhome}}"
      with_items:
       - {'usernname': 'mithun', 'createhome': 'no'}
       - {'usernname': 'mana', 'createhome': 'yes'}
       - {'usernname': 'ruthvik', 'createhome': 'no'}
       - {'usernname': 'shishir', 'createhome': 'yes'}
... 