---
- hosts: all
  become: true
  tasks: 
    - name: Install Apache HTTP Server
      tags:
        - install
      yum: name=httpd state=latest
    - name: Copy the index.html file
      tags:
       - copy
      copy:
       src: index.html
       dest: /var/www/html/index.html
    - name: Start the HTTP Server 
      tags: 
       - start
       - install
      service: name=httpd enabled=yes state=started
   
...